Fix poder mover formulario de boveda, y efecto al tirar un hechizo co…
ao-org/argentum20-client pull request #255
Opened 2023-10-05 23:22 UTC by carlospaezp

…n particula cuando el npc muere.

2023-10-07 10:59 UTC, morgolock requested changes

2023-10-07 10:59 UTC, morgolock commented on CODIGO/frmOpciones.frm
> +Private Sub CheckUI_MouseUp(Button As Integer, Shift As Integer, X As Single, Y As Single)
`byval Button As Integer, byval Shift As Integer, byval X As Single, byval Y As Single`

2023-10-07 10:59 UTC, morgolock commented on CODIGO/frmOpciones.frm
>  Private Sub chkInvertir_MouseUp(Button As Integer, Shift As Integer, x As Single, y As Single)
Missing `byval` in the parameters

2023-10-07 13:22 UTC, carlospaezp commented on CODIGO/frmOpciones.frm
> +Private Sub CheckUI_MouseUp(Button As Integer, Shift As Integer, X As Single, Y As Single)
ok, aunque el por defecto para integers y variables de ese estilo ya es ByVal

2023-10-08 14:04 UTC, matiascalegaris requested changes

2023-10-08 14:04 UTC, matiascalegaris commented on CODIGO/frmBancoObj.frm
> +
podemos sacar todas estas lineas en blanco que agrega los editores al pedo? es una funcion que solo llama a otra y ocupa 20 lineas de codigo

2023-10-08 17:48 UTC, morgolock commented on CODIGO/frmOpciones.frm
> +Private Sub CheckUI_MouseUp(Button As Integer, Shift As Integer, X As Single, Y As Single)
por convencio ponemos `byval`o `byref` obligatorio en todos los sub o funciones

si no pones nada no sabes si lo estas pasando por error byval o simplemente te olvidaste

2023-10-08 19:52 UTC, carlospaezp commented on CODIGO/frmOpciones.frm
> +Private Sub CheckUI_MouseUp(Button As Integer, Shift As Integer, X As Single, Y As Single)
lo intente cambiar a byval y no compila.. cuando son funcionas de eventos de formularios no podes cambiarlo

2023-10-08 21:13 UTC, matiascalegaris commented on CODIGO/frmOpciones.frm
> +Private Sub CheckUI_MouseUp(Button As Integer, Shift As Integer, X As Single, Y As Single)
estas funciones son auto generadas por los formularios, no puede cambiarse la firma de la funcion pablo

2023-10-09 18:34 UTC, matiascalegaris approved these changes

2023-10-09 18:39 UTC, morgolock approved these changes

2023-10-09 18:39 UTC, merged