Fix safe when was in new UI can be toggle with key S with the command…
ao-org/argentum20-client pull request #266
Opened 2023-10-23 20:45 UTC by carlospaezp

…, also now can move frmComerciar

2023-10-23 20:50 UTC, matiascalegaris requested changes

2023-10-23 20:50 UTC, matiascalegaris commented on CODIGO/Protocol.bas
> +    SeguroGame = True
si movemos esto aca, habria que borrar el seteo que se hace ne DibujarSeguroy Desdibujar seguro, estan al pedo

2023-10-23 21:16 UTC, carlospaezp commented on CODIGO/Protocol.bas
> +    SeguroGame = True
listo, me equivoque y lo cambie en el otro pr

2023-10-31 13:44 UTC, matiascalegaris approved these changes

2023-10-31 13:44 UTC, merged